### ISSUE TITLE
UICollectionView & AutoLayout issue

### ISSUE THREAD

**Issue by mheras** [bdbergeron/BDBSpinKitRefreshControl#4]
Hi,

I'm using a UICollectionView in a custom view controller with AutoLayout. I set it up so that it fills the entire view controller. I managed to add your control, but it is being displayed misaligned horizontally (not centered).

It might have to do with the fact that I'm using Interface Builder and that I didn't give any particular size to the view controller (I'm using iOS 8 size classes).

Any ideas?
Thanks,
Martin

P.S.: It would be AWESOME if the animation is not fired until the refreshing process starts. As it is implemented now, the animation starts as soon as we start dragging the scroll view a little bit.

**Comment by bdbergeron** [comment]
I just created a demo project using Storyboards/IB, and didn't have a problem with it. How are you adding the refresh control?

**Comment by bdbergeron** [comment]
Fixing issue #5 should solve this.
